trigger:
- main

variables:
  buildConfiguration: 'Release'

stages:
- stage: BuildJava
  jobs:
  - job: MavenBuild
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'java-app/pom.xml'
        goals: 'package'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'JUnit Tests (Maven)'
    
    - publish: $(System.DefaultWorkingDirectory)/java-app/target
      artifact: java-artifact

- stage: BuildPython
  dependsOn: BuildJava
  jobs:
  - job: PythonBuild
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    
    - script: pip install -r python-app/requirements.txt
      workingDirectory: 'python-app'
      displayName: 'Install dependencies'
    
    - script: python -m pytest tests/ -v --junitxml=test-results.xml
      workingDirectory: 'python-app'
      displayName: 'Run tests'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'python-app/test-results.xml'
        testRunTitle: 'Pytest Results'
    
    - publish: $(System.DefaultWorkingDirectory)/python-app
      artifact: python-artifact

- stage: DeployStaging
  dependsOn: BuildPython
  jobs:
  - job: DeployJava
    steps:
    - download: current
      artifact: java-artifact
    - script: echo "Deploying Java app to staging environment"
  
  - job: DeployPython
    steps:
    - download: current
      artifact: python-artifact
    - script: echo "Deploying Python app to staging environment"

- stage: DeployProduction
  dependsOn: DeployStaging
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: java-artifact
          - script: echo "Deploying Java app to production"
          
          - download: current
            artifact: python-artifact
          - script: echo "Deploying Python app to production"
