trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndTest
  jobs:
  - job: MavenBuild
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'java-app/pom.xml'
        goals: 'package'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'JUnit Tests (Maven)'
    
    - publish: $(System.DefaultWorkingDirectory)/java-app/target
      artifact: java-artifact

- stage: DeployDev
  dependsOn: BuildAndTest
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: java-artifact
    - script: echo "Deploying Java app to development environment"
