trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndTest
  jobs:
  - job: PythonTest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    
    - script: pip install -r python-app/requirements.txt
      workingDirectory: 'python-app'
      displayName: 'Install dependencies'
    
    - script: python -m pytest tests/ -v --junitxml=test-results.xml
      workingDirectory: 'python-app'
      displayName: 'Run tests'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'python-app/test-results.xml'
        testRunTitle: 'Pytest Results'
    
    - publish: $(System.DefaultWorkingDirectory)/python-app
      artifact: python-artifact

- stage: DeployDev
  dependsOn: BuildAndTest
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: python-artifact
    - script: echo "Deploying Python app to development environment"
